# Generated by Django 4.2.7 on 2025-11-03 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('core', '0002_default_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=120)),
                ('title', models.CharField(max_length=160)),
                ('contract_type', models.CharField(choices=[('PHOTO', 'Servicio Fotografía'), ('FRAME', 'Enmarcado'), ('GRAD', 'Graduaciones'), ('LASER', 'Corte Láser'), ('EVENT', 'Evento'), ('CUSTOM', 'Personalizado')], max_length=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('PENDING', 'Pendiente Aprobación'), ('ACTIVE', 'Activo'), ('SUSPENDED', 'Suspendido'), ('COMPLETED', 'Completado'), ('CANCELED', 'Cancelado')], db_index=True, default='DRAFT', max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('details', models.TextField(blank=True)),
                ('document', models.FileField(blank=True, upload_to='contracts/')),
                ('external_ref', models.CharField(blank=True, max_length=64)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='core_contracts', to='crm.client')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='core_contracts', to='core.tenant')),
            ],
            options={
                'db_table': 'core_contract',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='core_contra_tenant__f37271_idx'), models.Index(fields=['tenant', 'contract_type'], name='core_contra_tenant__7204c9_idx')],
            },
        ),
    ]
