# Generated by Django 5.2.4 on 2025-10-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[('impresora', 'Impresora'), ('equipo de oficina', 'Equipo de Oficina'), ('maquinaria', 'Maquinaria'), ('herramienta', 'Herramienta'), ('vehiculo', 'Vehículo')], max_length=50)),
                ('proveedor', models.CharField(max_length=255)),
                ('fecha_compra', models.DateField()),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo_pago', models.CharField(choices=[('contado', 'Contado'), ('financiado', 'Financiado'), ('leasing', 'Leasing')], max_length=20)),
                ('vida_util', models.PositiveIntegerField(help_text='Vida útil en meses')),
                ('depreciacion_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('en mantenimiento', 'En Mantenimiento'), ('inactivo', 'Inactivo')], max_length=20)),
            ],
        ),
    ]
