# Generated by Django 5.2.4 on 2025-10-30 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_activos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financiamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.CharField(choices=[('financiado', 'Financiado'), ('leasing', 'Leasing')], max_length=20)),
                ('entidad_financiera', models.CharField(max_length=255)),
                ('monto_financiado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cuotas_totales', models.PositiveIntegerField()),
                ('cuota_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('pagado', 'Pagado'), ('mora', 'Mora')], max_length=20)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financiamientos', to='gestion_activos.activo')),
            ],
        ),
    ]
