# Generated by Django 5.2.4 on 2025-10-30 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_activos', '0002_financiamiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_mantenimiento', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo'), ('emergencia', 'Emergencia')], max_length=20)),
                ('fecha_mantenimiento', models.DateField()),
                ('proveedor', models.CharField(max_length=255)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('en_progreso', 'En Progreso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], max_length=20)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='gestion_activos.activo')),
            ],
        ),
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('proveedor', models.CharField(max_length=255)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_compra', models.DateField()),
                ('cantidad', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('agotado', 'Agotado')], max_length=20)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repuestos', to='gestion_activos.activo')),
            ],
        ),
    ]
