# Generated by Django 5.2.7 on 2025-11-03 18:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_activos', '0003_mantenimiento_repuesto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mantenimiento',
            name='estado',
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='estado_del_activo',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('mantenimiento', 'Mantenimiento')], default='activo', max_length=20),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='estado_del_mantenimiento',
            field=models.CharField(choices=[('programado', 'Programado'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='programado', max_length=20),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='proxima_fecha_mantenimiento',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
