# Generated by Django 5.2.7 on 2025-11-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_activos', '0004_remove_mantenimiento_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repuesto',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='repuesto',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='repuesto',
            name='costo',
        ),
        migrations.RemoveField(
            model_name='repuesto',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='repuesto',
            name='fecha_compra',
        ),
        migrations.AddField(
            model_name='repuesto',
            name='categoria',
            field=models.CharField(choices=[('insumos impresoras', 'Insumos Impresoras'), ('repuestos impresoras', 'Repuestos Impresoras'), ('insumos camaras', 'Insumos Camaras'), ('repuestos camaras', 'Repuestos Camaras'), ('herramientas', 'Herramientas'), ('otros', 'Otros')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='codigo',
            field=models.CharField(default='0000000000', max_length=255),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='descripcion',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='stock_actual',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='stock_minimo',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='ubicacion',
            field=models.CharField(choices=[('almacen A', 'Almacen A'), ('almacen B', 'Almacen B'), ('estanteria 1', 'Estanteria 1'), ('estanteria 2', 'Estanteria B'), ('bodega', 'Bodega')], default='almacen A', max_length=20),
        ),
    ]
