# Generated by Django 4.2.7 on 2025-11-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subdomain', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('settings', models.JSONField(default=dict)),
                ('max_users', models.IntegerField(default=10)),
                ('max_storage_mb', models.IntegerField(default=1000)),
                ('features_enabled', models.JSONField(default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['subdomain'], name='core_tenant_subdoma_5ebe44_idx'), models.Index(fields=['is_active'], name='core_tenant_is_acti_99418a_idx')],
            },
        ),
    ]
