# Generated by Django 4.2.7 on 2025-10-30 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('Particular', 'Particular'), ('Colegio', 'Colegio'), ('Empresa', 'Empresa')], max_length=20)),
                ('contacto', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('ie', models.CharField(blank=True, max_length=100)),
                ('direccion', models.TextField(blank=True)),
                ('detalles', models.TextField(blank=True)),
                ('documento', models.CharField(blank=True, max_length=20)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('ultimo_pedido', models.DateField(blank=True, null=True)),
                ('total_pedidos', models.IntegerField(default=0)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('contract_type', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Activo', 'Activo'), ('Pendiente', 'Pendiente'), ('Pagado', 'Pagado'), ('Vencido', 'Vencido'), ('Completado', 'Completado')], max_length=20)),
                ('document', models.FileField(blank=True, upload_to='contracts/')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.client')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['tenant'], name='crm_contrac_tenant__d0fe42_idx'), models.Index(fields=['client'], name='crm_contrac_client__bc4391_idx'), models.Index(fields=['status'], name='crm_contrac_status_577ec7_idx'), models.Index(fields=['tenant', 'status'], name='crm_contrac_tenant__c4146f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['tenant'], name='crm_client_tenant__f2ddca_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['tenant', 'nombre'], name='crm_client_tenant__e5e881_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('tenant', 'documento')},
        ),
    ]
