# Generated by Django 4.2.7 on 2025-11-08 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('nombre', models.CharField(help_text='Nombre descriptivo para esta configuración', max_length=100, verbose_name='Nombre de la Configuración')),
                ('categoria', models.CharField(choices=[('ventas', 'Ventas'), ('inventario', 'Inventario'), ('produccion', 'Producción'), ('clientes', 'Clientes'), ('financiero', 'Financiero'), ('contratos', 'Contratos')], help_text='Categoría de reporte a la que aplica esta configuración', max_length=50, verbose_name='Categoría')),
                ('dias_por_defecto', models.IntegerField(default=30, help_text='Número de días hacia atrás para el rango de fechas por defecto', verbose_name='Días por Defecto')),
                ('activo', models.BooleanField(default=True, help_text='Indica si esta configuración está activa', verbose_name='Activo')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción adicional de la configuración', verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Configuración de Reporte',
                'verbose_name_plural': 'Configuraciones de Reportes',
                'ordering': ['categoria', 'nombre'],
            },
        ),
    ]
